dataset:
  name: cifar10
  variant: poisoned
model:
  script: configs/model/config_model.py
  framework: pytorch
pipeline:
  pre_training:
    tools:
      - pre_xgbod
      - pre_noop
  during_training:
    tools:
      - in_trades
      - in_noop
  post_training:
    tools:
      - post_fineprune
      - post_noop
  deployment:
    tools:
      - deploy_noop
