# LLM
dataset:
  name: cifar10
  variant: clean

model:
  script: configs/model/config_model_resnet20.py
  framework: pytorch

pipeline:
  pre_training:
    tools:
      - pre_noop_llm
  during_training:
    tools:
      - in_noop_llm
  post_training:
    tools:
      - post_noop_llm
  deployment:
    tools:
      - deploy_reef_llm
      - deploy_noop_llm

