dataset:
  name: cifar10
  link: https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
  format: pickle
  sha1: c58f30108f718f92721af3b95e74349a

pipeline:
  pre_training:
    tools:
      - name: feature-squeeze
        docker:
          image: ghcr.io/landseer-project/pre_squeeze:v1
          command: python defense.py --bit-depth 4
      - name: pre-dp
        docker:
          image: ghcr.io/landseer-project/pre_dp:v1
          command: python defense.py 
    noop:
      name: noop
      docker:
        image: ghcr.io/landseer-project/pre_noop:latest
        command: python main.py

  during_training:
    tools:
      - name: in-dp
        docker:
          image: ghcr.io/landseer-project/in_dp_fixed:v2
          command: python3 defense.py
    noop:
      name: in_noop
      docker:
        image: ghcr.io/landseer-project/in_noop:latest
        command: python main.py

  post_training:
    tools:
      - name: magnet
        docker:
          image: ghcr.io/landseer-project/post_magnet:v1
          command: python3 defense.py
