dataset:
  name: cifar10
  link: https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
  format: pickle
  sha1: c58f30108f718f92721af3b95e74349a

pipeline:
  pre_training:
    tools:
    - name: pre-squeeze
      docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/pre_squeeze:v1
      
    - docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/pre_xgbod:v2
      name: pre-xgbod
    - docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/pre_dp:v5
      name: pre-dp

    noop:
      name: noop
      docker:
        image: ghcr.io/landseer-project/pre_noop:v1
        command: python main.py

  during_training:
    tools:
    - name: in-trades
      docker:
        image: ghcr.io/landseer-project/in_trades:v1
        command: python3 main.py
    noop:
      name: in_noop
      docker:
        image: ghcr.io/landseer-project/in_noop:latest
        command: python main.py

  post_training:
    tools:
    - name: fine pruning
      docker:
        image: ghcr.io/landseer-project/post_fineprune:v1
        command: python3 main.py --prune-percentage 0.1
    - name: post_dp
      docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/post_dp:v3
      
