dataset:
  name: cifar10
  variant: clean
model:
  script: configs/model/config_model_resnet20.py
  framework: pytorch
pipeline:
  pre_training:
    tools:
      - pre_xgbod
      - tool: pre_watermarkbn
        command: python main.py --trigger_label 1 --exclude_target_class --trigger_size 12
      - pre_noop
  during_training:
    tools:
      - in_trades
      - in_noop
  post_training:
    tools:
      - post_magnet
      - post_neuronprune
      - post_noop
  deployment:
    tools:
      - deploy_explainshap
      - deploy_dataset_inference
      - deploy_noop