dataset:
  format: pickle
  link: https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
  name: cifar10
  sha1: dummy
pipeline:
  during_training:
    noop:
      docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/in_noop:v1
      name: in-noop
    tools:
    - docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/in_dp_fixed:v2
      name: in-dp-fixed
  post_training:
    tools:
    - docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/post_fineprune:v1
      name: post-fineprune
    - docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/post_dp:v3
      name: post-dp
  pre_training:
    noop:
      docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/pre_noop:v1
      name: pre-noop
    tools:
    - docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/pre_squeeze:v1
      name: pre-squeeze
    - docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/pre_xgbod:v2
      name: pre-xgbod
    - docker:
        command: python3 main.py
        config_script: configs/model/config_model.py
        image: ghcr.io/landseer-project/pre_dp:v5
      name: pre-dp
