FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-runtime

LABEL org.opencontainers.image.dataset="CIFAR-10"
LABEL org.opencontainers.image.defense_stage="during_training"
LABEL org.opencontainers.image.defense_type="noop"
LABEL org.opencontainers.image.framework="pytorch"

WORKDIR /app
COPY noop_in_landseer.py /app/main.py
COPY config_model.py /app/config_model.py
RUN pip install torchvision torch scikit-learn numpy

CMD ["python", "main.py", "--input_dir", "/data", "--output", "/output"]