# Use official PyTorch image with Python 3.9
FROM pytorch/pytorch:2.1.0-cuda11.8-cudnn8-runtime


LABEL org.opencontainers.image.dataset="CIFAR-10, CelebA"
LABEL org.opencontainers.image.defense_stage="during_training"
LABEL org.opencontainers.image.defense_type="outlier"
LABEL org.opencontainers.image.framework="pytorch"


# Set working directory
WORKDIR /app

# Copy all files into the container
COPY main.py ./
COPY loss.py ./
COPY data/ ./data/

# Install any Python dependencies (adjust as needed)
RUN pip install --upgrade pip && \
    pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 six numpy tqdm




